import Link from 'next/link';
import styles from './page.module.css';
import { Button } from '@/components/Button/Button';

export default function LandingPage() {
  return (
    <main className={styles.main}>
      {/* Navigation */}
      <nav className={styles.nav}>
        <div className={styles.logo}>
          <span className="text-gradient">AI Standup</span>
        </div>
        <div className={styles.navLinks}>
          <Link href="/login" className={styles.link}>Login</Link>
          <Link href="/register">
            <Button variant="glass">Get Started</Button>
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <section className={styles.hero}>
        <div className={`${styles.heroContent} animate-slide-up`}>
          <h1 className={styles.title}>
            Automate your daily standups with <span className="text-gradient">AI.</span>
          </h1>
          <p className={styles.subtitle}>
            Replace boring Zoom meetings. Team members drop quick async updates, 
            and our AI summarizes progress, highlights blockers, and delivers a daily digest.
          </p>
          <div className={styles.ctaGroup}>
            <Link href="/register">
              <Button variant="primary">Start for free</Button>
            </Link>
            <Link href="#features">
              <Button variant="secondary">Learn more</Button>
            </Link>
          </div>
        </div>
        
        {/* Decorative Background Elements */}
        <div className={styles.glowBlob1}></div>
        <div className={styles.glowBlob2}></div>
      </section>

      {/* Features Preview */}
      <section id="features" className={styles.features}>
        <div className={`${styles.featureCard} animate-slide-up`} style={{ animationDelay: '0.2s' }}>
          <h3>⚡ Async Updates</h3>
          <p>Drop your updates anytime. No more timezone conflicts or delayed meetings.</p>
        </div>
        <div className={`${styles.featureCard} animate-slide-up`} style={{ animationDelay: '0.4s' }}>
          <h3>🤖 AI Summaries</h3>
          <p>Get instant daily digests and weekly reports generated by AI.</p>
        </div>
        <div className={`${styles.featureCard} animate-slide-up`} style={{ animationDelay: '0.6s' }}>
          <h3>🚀 Blocker Detection</h3>
          <p>AI automatically detects blockers from text and notifies managers in real-time.</p>
        </div>
      </section>
    </main>
  );
}
